// Auto-generated by scripts/generate_service_content.py
// Do not edit manually.

export type ServiceCategory = 'digital-marketing' | 'it-manager-services' | 'programming';
export interface ServicePageContent {
  category: ServiceCategory;
  slug: string;
  title: string;
  subtitle: string;
  summary: string;
  content: string;
}

import digital_marketing_email_marketing from './digital-marketing/email-marketing.html?raw';
import digital_marketing_local_digital_presence_google_maps_apple_maps_etc from './digital-marketing/local-digital-presence-google-maps-apple-maps-etc.html?raw';
import digital_marketing_marketing_automation from './digital-marketing/marketing-automation.html?raw';
import digital_marketing_online_reputation_management from './digital-marketing/online-reputation-management.html?raw';
import digital_marketing_paid_advertising from './digital-marketing/paid-advertising.html?raw';
import digital_marketing_search_engine_optimization from './digital-marketing/search-engine-optimization.html?raw';
import digital_marketing_social_media_marketing from './digital-marketing/social-media-marketing.html?raw';
import digital_marketing_content_marketing from './digital-marketing/content-marketing.html?raw';
import it_manager_services_business_continuity_planning from './it-manager-services/business-continuity-planning.html?raw';
import it_manager_services_cloud_computing from './it-manager-services/cloud-computing.html?raw';
import it_manager_services_compliance_and_regulation_support from './it-manager-services/compliance-and-regulation-support.html?raw';
import it_manager_services_cybersecurity from './it-manager-services/cybersecurity.html?raw';
import it_manager_services_data_backup_and_recovery from './it-manager-services/data-backup-and-recovery.html?raw';
import it_manager_services_hardware_and_software_procurement from './it-manager-services/hardware-and-software-procurement.html?raw';
import it_manager_services_it_consulting_and_planning from './it-manager-services/it-consulting-and-planning.html?raw';
import it_manager_services_it_performance_reporting from './it-manager-services/it-performance-reporting.html?raw';
import it_manager_services_it_training_and_user_support from './it-manager-services/it-training-and-user-support.html?raw';
import it_manager_services_managed_email_services from './it-manager-services/managed-email-services.html?raw';
import it_manager_services_mdm_services from './it-manager-services/mdm-services.html?raw';
import it_manager_services_network_monitoring_and_management from './it-manager-services/network-monitoring-and-management.html?raw';
import it_manager_services_remote_it_support from './it-manager-services/remote-it-support.html?raw';
import it_manager_services_software_updates_and_patch_management from './it-manager-services/software-updates-and-patch-management.html?raw';
import it_manager_services_voip_solutions from './it-manager-services/voip-solutions.html?raw';
import programming_cloud_hosting_and_maintenance from './programming/cloud-hosting-and-maintenance.html?raw';
import programming_custom_api_integration from './programming/custom-api-integration.html?raw';
import programming_custom_website_design_and_development from './programming/custom-website-design-and-development.html?raw';
import programming_desktop_applications from './programming/desktop-applications.html?raw';
import programming_e_commerce_platform_solutions from './programming/e-commerce-platform-solutions.html?raw';
import programming_mobile_app_development from './programming/mobile-app-development.html?raw';
import programming_responsive_web_design from './programming/responsive-web-design.html?raw';
import programming_web_apps_and_portals from './programming/web-apps-and-portals.html?raw';
import programming_website_security_data_compliance_and_protection from './programming/website-security-data-compliance-and-protection.html?raw';

export const servicePages: ServicePageContent[] = [
  {
    category: "digital-marketing",
    slug: "email-marketing",
    title: "Email Marketing",
    subtitle: "Nurture Leads. Boost Sales. Stay Top-of-Mind.",
    summary: "Your Best Channel Might Already Be in Their Inbox Email isn't dead-it's one of the highest-performing channels in digital marketing. Our Email Marketing services help you turn subscribers into buyers with beautifully crafted, high-converting campaigns designed to engage, inform, and drive consistent revenue.",
    content: digital_marketing_email_marketing,
  },
  {
    category: "digital-marketing",
    slug: "local-digital-presence-google-maps-apple-maps-etc",
    title: "Local Digital Presence",
    subtitle: "Get Found First. Be Where Customers Search. Own Your Area.",
    summary: "If You're Not Showing Up on Maps, You're Missing Foot Traffic When customers search \"near me,\" they're not just browsing-they're ready to buy. Our Local Digital Presence services ensure your business appears where it matters most: Google Maps, Apple Maps, Bing Places, Yelp, and more.",
    content: digital_marketing_local_digital_presence_google_maps_apple_maps_etc,
  },
  {
    category: "digital-marketing",
    slug: "marketing-automation",
    title: "Marketing Automation",
    subtitle: "",
    summary: "Marketing Automation",
    content: digital_marketing_marketing_automation,
  },
  {
    category: "digital-marketing",
    slug: "online-reputation-management",
    title: "Online Reputation Management",
    subtitle: "Protect Your Brand. Control the Narrative. Build Lasting Trust.",
    summary: "If You Don't Manage Your Reputation, Google Will Do It for You One negative review, outdated article, or misleading comment can damage years of hard work. Our Online Reputation Management (ORM) services help you take back control-by monitoring, improving, and protecting how your business appears online.",
    content: digital_marketing_online_reputation_management,
  },
  {
    category: "digital-marketing",
    slug: "paid-advertising",
    title: "Paid Advertising",
    subtitle: "Target Smarter. Convert Faster. Maximize ROI.",
    summary: "You Don't Need a Bigger Budget-You Need Better Ads Throwing money at Facebook or Google doesn't guarantee results. Our Paid Advertising services are built to stretch your budget further, get your brand in front of the right people, and drive high-converting traffic that fuels real growth.",
    content: digital_marketing_paid_advertising,
  },
  {
    category: "digital-marketing",
    slug: "search-engine-optimization",
    title: "Search Engine Optimization (SEO)",
    subtitle: "Rank Higher. Get Found. Drive Consistent Traffic.",
    summary: "If You're Not Showing Up on Google, You're Missing Out Your website might look great-but if it's buried on page 3, no one's finding it. Our SEO services help you rise through the ranks, outrank competitors, and attract high-quality traffic that converts.",
    content: digital_marketing_search_engine_optimization,
  },
  {
    category: "digital-marketing",
    slug: "social-media-marketing",
    title: "Social Media Marketing",
    subtitle: "Grow Your Brand. Engage Your Audience. Drive Real Results.",
    summary: "If You're Not Posting with Purpose, You're Just Making Noise Likes are great-but we're here for loyalty, leads, and long-term growth. Our Social Media Marketing services help you show up consistently, connect authentically, and convert strategically across every major platform.",
    content: digital_marketing_social_media_marketing,
  },
  {
    category: "digital-marketing",
    slug: "content-marketing",
    title: "Tell Better Stories. Build Authority. Drive Organic Growth.",
    subtitle: "If You're Not Creating Value, You're Getting Ignored Your audience doesn't want ads-they want answers, insights, and connection. Our Content Marketing services help you create content that attracts, educates, and converts-turning your brand into a trusted source and authority in your space.",
    summary: "From blogs and case studies to ebooks and video scripts-we create strategic content that fuels SEO, supports sales, and builds long-term loyalty.",
    content: digital_marketing_content_marketing,
  },
  {
    category: "it-manager-services",
    slug: "business-continuity-planning",
    title: "Business Continuity Planning",
    subtitle: "Prepare for Anything. Recover from Everything.",
    summary: "Disasters Are Inevitable-Downtime Doesn't Have to Be",
    content: it_manager_services_business_continuity_planning,
  },
  {
    category: "it-manager-services",
    slug: "cloud-computing",
    title: "Cloud Computing Services",
    subtitle: "Scale Smarter. Work Anywhere. Pay for What You Use.",
    summary: "Bring Your Business to the Cloud-Securely and Seamlessly",
    content: it_manager_services_cloud_computing,
  },
  {
    category: "it-manager-services",
    slug: "compliance-and-regulation-support",
    title: "Compliance &amp; Regulation Support",
    subtitle: "Stay Compliant. Stay Secure. Stay in Business.",
    summary: "Avoid Fines, Breaches &amp; Headaches-Stay Ahead of the Rules",
    content: it_manager_services_compliance_and_regulation_support,
  },
  {
    category: "it-manager-services",
    slug: "cybersecurity",
    title: "Cybersecurity Services",
    subtitle: "Because One Breach Can End Everything.",
    summary: "Cyber Threats Are Constant-So Is Our Protection",
    content: it_manager_services_cybersecurity,
  },
  {
    category: "it-manager-services",
    slug: "data-backup-and-recovery",
    title: "Data Backup &amp; Recovery",
    subtitle: "Because Data Loss Should Never Be Permanent.",
    summary: "Protect Your Business From the Unexpected",
    content: it_manager_services_data_backup_and_recovery,
  },
  {
    category: "it-manager-services",
    slug: "hardware-and-software-procurement",
    title: "Hardware &amp; Software Procurement",
    subtitle: "Simplify the Buying. Elevate the Doing.",
    summary: "Get the Right Tech-Without the Guesswork",
    content: it_manager_services_hardware_and_software_procurement,
  },
  {
    category: "it-manager-services",
    slug: "it-consulting-and-planning",
    title: "IT Consulting &amp; Planning",
    subtitle: "Smart Strategy. Real Results.",
    summary: "IT Should Drive Growth-Not Just Solve Problems",
    content: it_manager_services_it_consulting_and_planning,
  },
  {
    category: "it-manager-services",
    slug: "it-performance-reporting",
    title: "IT Performance Reporting",
    subtitle: "Clarity That Drives Smart IT Decisions.",
    summary: "If You Can't Measure It, You Can't Improve It",
    content: it_manager_services_it_performance_reporting,
  },
  {
    category: "it-manager-services",
    slug: "it-training-and-user-support",
    title: "IT Training &amp; User Support",
    subtitle: "Empower Your People. Elevate Your Tech.",
    summary: "Because Technology is Only as Powerful as the People Using It",
    content: it_manager_services_it_training_and_user_support,
  },
  {
    category: "it-manager-services",
    slug: "managed-email-services",
    title: "Managed Email Services",
    subtitle: "Secure. Scalable. Stress-Free.",
    summary: "Professional Email That Just Works",
    content: it_manager_services_managed_email_services,
  },
  {
    category: "it-manager-services",
    slug: "mdm-services",
    title: "Mobile Device Management (MDM) Services",
    subtitle: "Secure Your Devices. Empower Your Team.",
    summary: "Control Every Device Without Holding It",
    content: it_manager_services_mdm_services,
  },
  {
    category: "it-manager-services",
    slug: "network-monitoring-and-management",
    title: "Network Monitoring and Management",
    subtitle: "Proactive. Predictable. Powerful.",
    summary: "Stay Ahead of Downtime-Before It Happens",
    content: it_manager_services_network_monitoring_and_management,
  },
  {
    category: "it-manager-services",
    slug: "remote-it-support",
    title: "Remote IT Support - Built for Speed, Built for Trust",
    subtitle: "We keep your business running, even when your tech doesn't.",
    summary: "What Is Remote IT Support?",
    content: it_manager_services_remote_it_support,
  },
  {
    category: "it-manager-services",
    slug: "software-updates-and-patch-management",
    title: "Software Updates &amp; Patch Management",
    subtitle: "Stay Secure. Stay Updated. Stay Ahead.",
    summary: "Outdated Software is an Open Door to Cyber Threats",
    content: it_manager_services_software_updates_and_patch_management,
  },
  {
    category: "it-manager-services",
    slug: "voip-solutions",
    title: "VoIP Solutions",
    subtitle: "Modern Communication. Anywhere, Anytime.",
    summary: "Your Phone System, Upgraded",
    content: it_manager_services_voip_solutions,
  },
  {
    category: "programming",
    slug: "cloud-hosting-and-maintenance",
    title: "Cloud Hosting And Maintenance",
    subtitle: "",
    summary: "Cloud Hosting And Maintenance",
    content: programming_cloud_hosting_and_maintenance,
  },
  {
    category: "programming",
    slug: "custom-api-integration",
    title: "Custom API Integration",
    subtitle: "Connect Everything. Automate Anything. Unlock Growth.",
    summary: "Your Tools Should Talk to Each Other If your systems, apps, and data sources aren't connected-you're losing time, money, and momentum. Our Custom API Integration services help you bridge the gaps between platforms, automate manual workflows, and create a seamless ecosystem that just works.",
    content: programming_custom_api_integration,
  },
  {
    category: "programming",
    slug: "custom-website-design-and-development",
    title: "Custom Website Design &amp; Development",
    subtitle: "Built for Your Brand. Engineered for Results.",
    summary: "Your Website Shouldn't Just Look Good-It Should Work Hard",
    content: programming_custom_website_design_and_development,
  },
  {
    category: "programming",
    slug: "desktop-applications",
    title: "Desktop Application Development",
    subtitle: "Build Powerful Software. Run It Anywhere.",
    summary: "Your Business Deserves More Than a Browser Web apps are great-but when performance, offline access, or system-level control matters, desktop applications deliver. Our Desktop Application Services help you build robust, high-performing software solutions that work across Windows, macOS, and Linux.",
    content: programming_desktop_applications,
  },
  {
    category: "programming",
    slug: "e-commerce-platform-solutions",
    title: "E-Commerce Platform Solutions",
    subtitle: "Sell Smarter. Scale Faster. Seamlessly Online.",
    summary: "Your Store Deserves More Than Just a Checkout Page",
    content: programming_e_commerce_platform_solutions,
  },
  {
    category: "programming",
    slug: "mobile-app-development",
    title: "Mobile App Development",
    subtitle: "Your App. Your Brand. In Every Pocket.",
    summary: "If You're Not Mobile, You're Missing Out People don't just browse on mobile-theyliveon it. From on-demand services to loyalty apps and internal tools, our Mobile App Development services help you launch user-friendly, feature-rich apps that work flawlessly on iOS and Android.",
    content: programming_mobile_app_development,
  },
  {
    category: "programming",
    slug: "responsive-web-design",
    title: "Responsive Web Design Services",
    subtitle: "One Website. Every Screen. Every User.",
    summary: "Your Audience Is Mobile-Is Your Website Ready?",
    content: programming_responsive_web_design,
  },
  {
    category: "programming",
    slug: "web-apps-and-portals",
    title: "Web Apps &amp; Portals",
    subtitle: "Launch Faster. Scale Smarter. Connect Better.",
    summary: "Your Digital Hub-Custom-Built for Results Whether you're building a client portal, internal dashboard, or full-scale SaaS platform, web apps are the backbone of modern business. Our Web App &amp; Portal Development services help you turn your vision into a fast, secure, and scalable digital experience-accessible from any device, anywhere.",
    content: programming_web_apps_and_portals,
  },
  {
    category: "programming",
    slug: "website-security-data-compliance-and-protection",
    title: "Website Security, Data Compliance &amp; Protection",
    subtitle: "Guard Your Site. Protect Your Data. Stay Compliant.",
    summary: "If You Have a Website, You're a Target",
    content: programming_website_security_data_compliance_and_protection,
  },
]
